[package]
name = "inmemodb"
version = "0.1.0"
edition = "2021"
authors = ["Cem Guler <cem.guler@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }